version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  job-service:
    build: ./job-service
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/jobs_db
      - RABBITMQ_URL=amqp://user:pass@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3001:3001"

  applicant-service:
    build: ./applicant-service
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017/applicants_db
      - JOB_SERVICE_URL=http://job-service:3001
      - RABBITMQ_URL=amqp://user:pass@rabbitmq:5672
    depends_on:
      - job-service
      - mongo
      - rabbitmq
    ports:
      - "3002:3002"

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - job-service
      - applicant-service

volumes:
  mongo-data:
